### ISSUE TITLE
Réparer la génération PDF

### ISSUE THREAD

**Issue by cbenz** [etalab/validata.etalab.studio#1]
En rapport avec https://git.opendatafrance.net/validata/validata-ui/-/issues/71

La génération PDF utilise Chromium headless qui est inclus dans par l'image Docker (cf [Dockerfile](https://git.opendatafrance.net/validata/validata-ui/-/blob/4ad611ae5b0b02a619ffe42787be7ee8b984ad7c/Dockerfile#L9)).

Dokku n'utilisant pas les images Docker je suppose que l'erreur vient de là. Cela pourrait être confirmé en regardant les logs Dokku du "dyno" validata-ui.

Manifestement la config utilise un [runtime Python](https://github.com/abulte/validata-ui-dokku/blob/master/runtime.txt) et n'installe pas Chromium. N'ayant jamais utilisé Dokku, je ne sais pas si on peut préciser d'installer des paquets comme Chromium.

Sinon j'ai quand même regardé la doc et il semble que l'on puisse déployer un "dyno" depuis une image docker (cf [doc](http://dokku.viewdocs.io/dokku/deployment/methods/images/)) mais vous êtes sûrement déjà au courant. Cela permettrait de rester synchro avec les images produites par Validata de toutes façons.

**Comment by abulte** [comment]
En effet, il va falloir un Dockerfile custom pour gérer ça, mais ça se fait. Merci !
